import Navbar from '@/app/components/Navbar'
import Sidebar from '@/app/components/Sidebar'

export const metadata = {
  title: 'My Profile',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
    children, // will be a page or nested layout
  }: {
    children: React.ReactNode
  }) {
    return (
        <>
        <Sidebar></Sidebar>
        {/* <Navbar></Navbar> */}
        {children}
        </>
    )
  }